name: workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit Test
      run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker -q
      - name: Deploy to Google Cloud Container Registry
        env:
            GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker build -t us.gcr.io/$GCP_PROJECT_ID/gcloud_run_demo_py:$TAG .
          docker push us.gcr.io/$GCP_PROJECT_ID/gcloud_run_demo_py:$TAG
          docker tag us.gcr.io/$GCP_PROJECT_ID/gcloud_run_demo_py:$TAG us.gcr.io/$GCP_PROJECT_ID/gcloud_run_demo_py:latest
          docker push us.gcr.io/$GCP_PROJECT_ID/gcloud_run_demo_py:latest
      - name: Deploy to Google Cloud Run
        run: |
          sed -i 's/{TAG}/$TAG/g' gcloud_service.yaml
          cat gcloud_service.yaml
          gcloud beta run services replace gcloud_service.yaml --platform managed --region us-central1